name: Bug Report
description: Report a bug or unexpected behavior in a feature or the repo workflow
title: "[BUG] <short description of the bug>"
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the following information to help us reproduce and fix the issue.

  - type: input
    id: description
    attributes:
      label: Description
      description: A short summary of the bug
      placeholder: e.g. "LinkedList insert() fails on empty list"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What steps do we need to follow to see the bug?
      placeholder: |
        1. Run `npm test`
        2. Observe failure in `linked-list.test.ts`
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The insert method should return true and update the head node.

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: It throws a "Cannot read property 'next' of null" error.

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which area of the code is affected?
      options:
        - Data Structure Implementation (e.g. src/)
        - Tests (e.g. tests/)
        - CI / GitHub Actions
        - Repo Workflow / Templates
        - Other
      default: 0
