name: Feature Request
description: Propose adding a new feature, enhancement, or tooling improvement
title: "[FEATURE] <brief description of the feature>"
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the details below to help scope and track this enhancement.

  - type: input
    id: feature-title
    attributes:
      label: Feature Title
      description: Name of the data structure or feature to be added
      placeholder: e.g. "Add Doubly Linked List"

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What kind of feature is this?
      options:
        - Data Structure (e.g. Stack, Tree, Graph)
        - Algorithm (e.g. Sorting, Searching)
        - Test Coverage Improvement
        - CI/Repo Workflow Enhancement
        - Documentation
        - Other
      default: 0

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is this feature and why is it valuable to add?
      placeholder: |
        Describe what this data structure or feature is, and why it's important for the repo.
        E.g. "A doubly linked list allows traversal in both directions and is useful for implementing deques or LRU caches."

    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements & Scope
      description: What are the key tasks for this feature?
      placeholder: |
        - Implement insert and delete methods
        - Add unit tests
        - Write integration test (if needed)
        - Add entry to `solution-explanations.md`
        - Document time/space complexity
      value: |
        - [ ] Write implementation
        - [ ] Write unit tests
        - [ ] Add integration test (if needed)
        - [ ] Update solution-explanations.md
        - [ ] Run lint, type-check, and tests
